# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/core.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v1.Relationship" do
    optional :resource, :message, 1, "authzed.api.v1.ObjectReference"
    optional :relation, :string, 2
    optional :subject, :message, 3, "authzed.api.v1.SubjectReference"
  end
  add_message "authzed.api.v1.SubjectReference" do
    optional :object, :message, 1, "authzed.api.v1.ObjectReference"
    optional :optional_relation, :string, 2
  end
  add_message "authzed.api.v1.ObjectReference" do
    optional :object_type, :string, 1
    optional :object_id, :string, 2
  end
  add_message "authzed.api.v1.ZedToken" do
    optional :token, :string, 1
  end
  add_message "authzed.api.v1.RelationshipUpdate" do
    optional :operation, :enum, 1, "authzed.api.v1.RelationshipUpdate.Operation"
    optional :relationship, :message, 2, "authzed.api.v1.Relationship"
  end
  add_enum "authzed.api.v1.RelationshipUpdate.Operation" do
    value :OPERATION_UNSPECIFIED, 0
    value :OPERATION_CREATE, 1
    value :OPERATION_TOUCH, 2
    value :OPERATION_DELETE, 3
  end
  add_message "authzed.api.v1.PermissionRelationshipTree" do
    optional :expanded_object, :message, 3, "authzed.api.v1.ObjectReference"
    optional :expanded_relation, :string, 4
    oneof :tree_type do
      optional :intermediate, :message, 1, "authzed.api.v1.AlgebraicSubjectSet"
      optional :leaf, :message, 2, "authzed.api.v1.DirectSubjectSet"
    end
  end
  add_message "authzed.api.v1.AlgebraicSubjectSet" do
    optional :operation, :enum, 1, "authzed.api.v1.AlgebraicSubjectSet.Operation"
    repeated :children, :message, 2, "authzed.api.v1.PermissionRelationshipTree"
  end
  add_enum "authzed.api.v1.AlgebraicSubjectSet.Operation" do
    value :OPERATION_UNSPECIFIED, 0
    value :OPERATION_UNION, 1
    value :OPERATION_INTERSECTION, 2
    value :OPERATION_EXCLUSION, 3
  end
  add_message "authzed.api.v1.DirectSubjectSet" do
    repeated :subjects, :message, 1, "authzed.api.v1.SubjectReference"
  end
end

module Authzed
  module Api
    module V1
      Relationship = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.Relationship").msgclass
      SubjectReference = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.SubjectReference").msgclass
      ObjectReference = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ObjectReference").msgclass
      ZedToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ZedToken").msgclass
      RelationshipUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.RelationshipUpdate").msgclass
      RelationshipUpdate::Operation = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.RelationshipUpdate.Operation").enummodule
      PermissionRelationshipTree = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.PermissionRelationshipTree").msgclass
      AlgebraicSubjectSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.AlgebraicSubjectSet").msgclass
      AlgebraicSubjectSet::Operation = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.AlgebraicSubjectSet.Operation").enummodule
      DirectSubjectSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.DirectSubjectSet").msgclass
    end
  end
end
