# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/core.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'validate/validate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v1/core.proto", :syntax => :proto3) do
    add_message "authzed.api.v1.Relationship" do
      optional :resource, :message, 1, "authzed.api.v1.ObjectReference", json_name: "resource"
      optional :relation, :string, 2, json_name: "relation"
      optional :subject, :message, 3, "authzed.api.v1.SubjectReference", json_name: "subject"
      optional :optional_caveat, :message, 4, "authzed.api.v1.ContextualizedCaveat", json_name: "optionalCaveat"
    end
    add_message "authzed.api.v1.ContextualizedCaveat" do
      optional :caveat_name, :string, 1, json_name: "caveatName"
      optional :context, :message, 2, "google.protobuf.Struct", json_name: "context"
    end
    add_message "authzed.api.v1.SubjectReference" do
      optional :object, :message, 1, "authzed.api.v1.ObjectReference", json_name: "object"
      optional :optional_relation, :string, 2, json_name: "optionalRelation"
    end
    add_message "authzed.api.v1.ObjectReference" do
      optional :object_type, :string, 1, json_name: "objectType"
      optional :object_id, :string, 2, json_name: "objectId"
    end
    add_message "authzed.api.v1.ZedToken" do
      optional :token, :string, 1, json_name: "token"
    end
    add_message "authzed.api.v1.RelationshipUpdate" do
      optional :operation, :enum, 1, "authzed.api.v1.RelationshipUpdate.Operation", json_name: "operation"
      optional :relationship, :message, 2, "authzed.api.v1.Relationship", json_name: "relationship"
    end
    add_enum "authzed.api.v1.RelationshipUpdate.Operation" do
      value :OPERATION_UNSPECIFIED, 0
      value :OPERATION_CREATE, 1
      value :OPERATION_TOUCH, 2
      value :OPERATION_DELETE, 3
    end
    add_message "authzed.api.v1.PermissionRelationshipTree" do
      optional :expanded_object, :message, 3, "authzed.api.v1.ObjectReference", json_name: "expandedObject"
      optional :expanded_relation, :string, 4, json_name: "expandedRelation"
      oneof :tree_type do
        optional :intermediate, :message, 1, "authzed.api.v1.AlgebraicSubjectSet", json_name: "intermediate"
        optional :leaf, :message, 2, "authzed.api.v1.DirectSubjectSet", json_name: "leaf"
      end
    end
    add_message "authzed.api.v1.AlgebraicSubjectSet" do
      optional :operation, :enum, 1, "authzed.api.v1.AlgebraicSubjectSet.Operation", json_name: "operation"
      repeated :children, :message, 2, "authzed.api.v1.PermissionRelationshipTree", json_name: "children"
    end
    add_enum "authzed.api.v1.AlgebraicSubjectSet.Operation" do
      value :OPERATION_UNSPECIFIED, 0
      value :OPERATION_UNION, 1
      value :OPERATION_INTERSECTION, 2
      value :OPERATION_EXCLUSION, 3
    end
    add_message "authzed.api.v1.DirectSubjectSet" do
      repeated :subjects, :message, 1, "authzed.api.v1.SubjectReference", json_name: "subjects"
    end
  end
end

module Authzed
  module Api
    module V1
      Relationship = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.Relationship").msgclass
      ContextualizedCaveat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ContextualizedCaveat").msgclass
      SubjectReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.SubjectReference").msgclass
      ObjectReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ObjectReference").msgclass
      ZedToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ZedToken").msgclass
      RelationshipUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.RelationshipUpdate").msgclass
      RelationshipUpdate::Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.RelationshipUpdate.Operation").enummodule
      PermissionRelationshipTree = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.PermissionRelationshipTree").msgclass
      AlgebraicSubjectSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.AlgebraicSubjectSet").msgclass
      AlgebraicSubjectSet::Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.AlgebraicSubjectSet.Operation").enummodule
      DirectSubjectSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.DirectSubjectSet").msgclass
    end
  end
end
