# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/error_reason.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v1/error_reason.proto", :syntax => :proto3) do
    add_enum "authzed.api.v1.ErrorReason" do
      value :ERROR_REASON_UNSPECIFIED, 0
      value :ERROR_REASON_SCHEMA_PARSE_ERROR, 1
      value :ERROR_REASON_SCHEMA_TYPE_ERROR, 2
      value :ERROR_REASON_UNKNOWN_DEFINITION, 3
      value :ERROR_REASON_UNKNOWN_RELATION_OR_PERMISSION, 4
      value :ERROR_REASON_TOO_MANY_UPDATES_IN_REQUEST, 5
      value :ERROR_REASON_TOO_MANY_PRECONDITIONS_IN_REQUEST, 6
      value :ERROR_REASON_WRITE_OR_DELETE_PRECONDITION_FAILURE, 7
      value :ERROR_REASON_SERVICE_READ_ONLY, 8
      value :ERROR_REASON_UNKNOWN_CAVEAT, 9
      value :ERROR_REASON_INVALID_SUBJECT_TYPE, 10
      value :ERROR_REASON_CAVEAT_PARAMETER_TYPE_ERROR, 11
      value :ERROR_REASON_UPDATES_ON_SAME_RELATIONSHIP, 12
      value :ERROR_REASON_CANNOT_UPDATE_PERMISSION, 13
    end
  end
end

module Authzed
  module Api
    module V1
      ErrorReason = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ErrorReason").enummodule
    end
  end
end
