# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/openapi.proto

require 'google/protobuf'

require 'protoc-gen-openapiv2/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v1/openapi.proto", :syntax => :proto3) do
  end
end

module Authzed
  module Api
    module V1
    end
  end
end
