# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/permission_service.proto

require 'google/protobuf'

require 'authzed/api/v1/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v1.Consistency" do
    oneof :requirement do
      optional :minimize_latency, :bool, 1
      optional :at_least_as_fresh, :message, 2, "authzed.api.v1.ZedToken"
      optional :at_exact_snapshot, :message, 3, "authzed.api.v1.ZedToken"
      optional :fully_consistent, :bool, 4
    end
  end
  add_message "authzed.api.v1.RelationshipFilter" do
    optional :resource_type, :string, 1
    optional :optional_resource_id, :string, 2
    optional :optional_relation, :string, 3
    optional :optional_subject_filter, :message, 4, "authzed.api.v1.SubjectFilter"
  end
  add_message "authzed.api.v1.SubjectFilter" do
    optional :subject_type, :string, 1
    optional :optional_subject_id, :string, 2
    optional :optional_relation, :message, 3, "authzed.api.v1.SubjectFilter.RelationFilter"
  end
  add_message "authzed.api.v1.SubjectFilter.RelationFilter" do
    optional :relation, :string, 1
  end
  add_message "authzed.api.v1.ReadRelationshipsRequest" do
    optional :consistency, :message, 1, "authzed.api.v1.Consistency"
    optional :relationship_filter, :message, 2, "authzed.api.v1.RelationshipFilter"
  end
  add_message "authzed.api.v1.ReadRelationshipsResponse" do
    optional :read_at, :message, 1, "authzed.api.v1.ZedToken"
    optional :relationship, :message, 2, "authzed.api.v1.Relationship"
  end
  add_message "authzed.api.v1.Precondition" do
    optional :operation, :enum, 1, "authzed.api.v1.Precondition.Operation"
    optional :filter, :message, 2, "authzed.api.v1.RelationshipFilter"
  end
  add_enum "authzed.api.v1.Precondition.Operation" do
    value :OPERATION_UNSPECIFIED, 0
    value :OPERATION_MUST_NOT_MATCH, 1
    value :OPERATION_MUST_MATCH, 2
  end
  add_message "authzed.api.v1.WriteRelationshipsRequest" do
    repeated :updates, :message, 1, "authzed.api.v1.RelationshipUpdate"
    repeated :optional_preconditions, :message, 2, "authzed.api.v1.Precondition"
  end
  add_message "authzed.api.v1.WriteRelationshipsResponse" do
    optional :written_at, :message, 1, "authzed.api.v1.ZedToken"
  end
  add_message "authzed.api.v1.DeleteRelationshipsRequest" do
    optional :relationship_filter, :message, 1, "authzed.api.v1.RelationshipFilter"
    repeated :optional_preconditions, :message, 2, "authzed.api.v1.Precondition"
  end
  add_message "authzed.api.v1.DeleteRelationshipsResponse" do
    optional :deleted_at, :message, 1, "authzed.api.v1.ZedToken"
  end
  add_message "authzed.api.v1.CheckPermissionRequest" do
    optional :consistency, :message, 1, "authzed.api.v1.Consistency"
    optional :resource, :message, 2, "authzed.api.v1.ObjectReference"
    optional :permission, :string, 3
    optional :subject, :message, 4, "authzed.api.v1.SubjectReference"
  end
  add_message "authzed.api.v1.CheckPermissionResponse" do
    optional :checked_at, :message, 1, "authzed.api.v1.ZedToken"
    optional :permissionship, :enum, 2, "authzed.api.v1.CheckPermissionResponse.Permissionship"
  end
  add_enum "authzed.api.v1.CheckPermissionResponse.Permissionship" do
    value :PERMISSIONSHIP_UNSPECIFIED, 0
    value :PERMISSIONSHIP_NO_PERMISSION, 1
    value :PERMISSIONSHIP_HAS_PERMISSION, 2
  end
  add_message "authzed.api.v1.ExpandPermissionTreeRequest" do
    optional :consistency, :message, 1, "authzed.api.v1.Consistency"
    optional :resource, :message, 2, "authzed.api.v1.ObjectReference"
    optional :permission, :string, 3
  end
  add_message "authzed.api.v1.ExpandPermissionTreeResponse" do
    optional :expanded_at, :message, 1, "authzed.api.v1.ZedToken"
    optional :tree_root, :message, 2, "authzed.api.v1.PermissionRelationshipTree"
  end
  add_message "authzed.api.v1.LookupResourcesRequest" do
    optional :consistency, :message, 1, "authzed.api.v1.Consistency"
    optional :resource_object_type, :string, 2
    optional :permission, :string, 3
    optional :subject, :message, 4, "authzed.api.v1.SubjectReference"
  end
  add_message "authzed.api.v1.LookupResourcesResponse" do
    optional :looked_up_at, :message, 1, "authzed.api.v1.ZedToken"
    optional :resource_object_id, :string, 2
  end
end

module Authzed
  module Api
    module V1
      Consistency = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.Consistency").msgclass
      RelationshipFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.RelationshipFilter").msgclass
      SubjectFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.SubjectFilter").msgclass
      SubjectFilter::RelationFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.SubjectFilter.RelationFilter").msgclass
      ReadRelationshipsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ReadRelationshipsRequest").msgclass
      ReadRelationshipsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ReadRelationshipsResponse").msgclass
      Precondition = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.Precondition").msgclass
      Precondition::Operation = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.Precondition.Operation").enummodule
      WriteRelationshipsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.WriteRelationshipsRequest").msgclass
      WriteRelationshipsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.WriteRelationshipsResponse").msgclass
      DeleteRelationshipsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.DeleteRelationshipsRequest").msgclass
      DeleteRelationshipsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.DeleteRelationshipsResponse").msgclass
      CheckPermissionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.CheckPermissionRequest").msgclass
      CheckPermissionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.CheckPermissionResponse").msgclass
      CheckPermissionResponse::Permissionship = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.CheckPermissionResponse.Permissionship").enummodule
      ExpandPermissionTreeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ExpandPermissionTreeRequest").msgclass
      ExpandPermissionTreeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ExpandPermissionTreeResponse").msgclass
      LookupResourcesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.LookupResourcesRequest").msgclass
      LookupResourcesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.LookupResourcesResponse").msgclass
    end
  end
end
