# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/schema_service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'validate/validate_pb'
require 'authzed/api/v1/core_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v1/schema_service.proto", :syntax => :proto3) do
    add_message "authzed.api.v1.ReadSchemaRequest" do
    end
    add_message "authzed.api.v1.ReadSchemaResponse" do
      optional :schema_text, :string, 1, json_name: "schemaText"
      optional :read_at, :message, 2, "authzed.api.v1.ZedToken", json_name: "readAt"
    end
    add_message "authzed.api.v1.WriteSchemaRequest" do
      optional :schema, :string, 1, json_name: "schema"
    end
    add_message "authzed.api.v1.WriteSchemaResponse" do
      optional :written_at, :message, 1, "authzed.api.v1.ZedToken", json_name: "writtenAt"
    end
  end
end

module Authzed
  module Api
    module V1
      ReadSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ReadSchemaRequest").msgclass
      ReadSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ReadSchemaResponse").msgclass
      WriteSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.WriteSchemaRequest").msgclass
      WriteSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.WriteSchemaResponse").msgclass
    end
  end
end
