# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/schema.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v1/schema.proto", :syntax => :proto3) do
    add_message "authzed.api.v1.ReadSchemaRequest" do
    end
    add_message "authzed.api.v1.ReadSchemaResponse" do
      optional :schema_text, :string, 1, json_name: "schemaText"
    end
    add_message "authzed.api.v1.WriteSchemaRequest" do
      optional :schema, :string, 1, json_name: "schema"
    end
    add_message "authzed.api.v1.WriteSchemaResponse" do
    end
  end
end

module Authzed
  module Api
    module V1
      ReadSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ReadSchemaRequest").msgclass
      ReadSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.ReadSchemaResponse").msgclass
      WriteSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.WriteSchemaRequest").msgclass
      WriteSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1.WriteSchemaResponse").msgclass
    end
  end
end
