# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authzed/api/v1/watch_service.proto for package 'authzed.api.v1'

require 'grpc'
require 'authzed/api/v1/watch_service_pb'

module Authzed
  module Api
    module V1
      module WatchService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'authzed.api.v1.WatchService'

          rpc :Watch, ::Authzed::Api::V1::WatchRequest, stream(::Authzed::Api::V1::WatchResponse)
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
