# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/schema.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v1alpha1/schema.proto", :syntax => :proto3) do
    add_message "authzed.api.v1alpha1.ReadSchemaRequest" do
      repeated :object_definitions_names, :string, 1, json_name: "objectDefinitionsNames"
    end
    add_message "authzed.api.v1alpha1.ReadSchemaResponse" do
      repeated :object_definitions, :string, 1, json_name: "objectDefinitions"
      optional :computed_definitions_revision, :string, 2, json_name: "computedDefinitionsRevision"
    end
    add_message "authzed.api.v1alpha1.WriteSchemaRequest" do
      optional :schema, :string, 1, json_name: "schema"
      optional :optional_definitions_revision_precondition, :string, 2, json_name: "optionalDefinitionsRevisionPrecondition"
    end
    add_message "authzed.api.v1alpha1.WriteSchemaResponse" do
      repeated :object_definitions_names, :string, 1, json_name: "objectDefinitionsNames"
      optional :computed_definitions_revision, :string, 2, json_name: "computedDefinitionsRevision"
    end
  end
end

module Authzed
  module Api
    module V1alpha1
      ReadSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1alpha1.ReadSchemaRequest").msgclass
      ReadSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1alpha1.ReadSchemaResponse").msgclass
      WriteSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1alpha1.WriteSchemaRequest").msgclass
      WriteSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v1alpha1.WriteSchemaResponse").msgclass
    end
  end
end
