# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authzed/api/v1alpha1/watchresources_service.proto for package 'authzed.api.v1alpha1'

require 'grpc'
require 'authzed/api/v1alpha1/watchresources_service_pb'

module Authzed
  module Api
    module V1alpha1
      module WatchResourcesService
        # WatchResourcesService is used to receive a stream of updates for resources of a
        # specific (resource type, permission, subject) combination.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'authzed.api.v1alpha1.WatchResourcesService'

          # WatchResources initiates a watch for permission changes for the provided
          # (resource type, permission, subject) pair.
          rpc :WatchResources, ::Authzed::Api::V1alpha1::WatchResourcesRequest, stream(::Authzed::Api::V1alpha1::WatchResourcesResponse)
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
