# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arrakisapi/api/acl_service.proto

require 'google/protobuf'

require 'arrakisapi/api/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("arrakisapi/api/acl_service.proto", :syntax => :proto3) do
    add_message "RelationTupleFilter" do
      optional :namespace, :string, 1
      optional :object_id, :string, 2
      optional :relation, :string, 3
      optional :user_id, :string, 4
      optional :userset, :message, 5, "ObjectAndRelation"
      repeated :filters, :enum, 6, "RelationTupleFilter.Filter"
    end
    add_enum "RelationTupleFilter.Filter" do
      value :UNKNOWN, 0
      value :OBJECT_ID, 1
      value :RELATION, 2
      value :USER_ID, 3
      value :USERSET, 4
    end
    add_message "ReadRequest" do
      repeated :tuplesets, :message, 1, "RelationTupleFilter"
      optional :at_revision, :message, 2, "Zookie"
    end
    add_message "ReadResponse" do
      repeated :tuplesets, :message, 1, "ReadResponse.Tupleset"
      optional :revision, :message, 2, "Zookie"
    end
    add_message "ReadResponse.Tupleset" do
      repeated :tuples, :message, 1, "RelationTuple"
    end
    add_message "WriteRequest" do
      repeated :write_conditions, :message, 1, "RelationTuple"
      repeated :updates, :message, 2, "RelationTupleUpdate"
    end
    add_message "WriteResponse" do
      optional :revision, :message, 1, "Zookie"
    end
    add_message "CheckRequest" do
      optional :test_userset, :message, 1, "ObjectAndRelation"
      optional :user, :message, 2, "User"
      optional :at_revision, :message, 3, "Zookie"
    end
    add_message "ContentChangeCheckRequest" do
      optional :test_userset, :message, 1, "ObjectAndRelation"
      optional :user, :message, 2, "User"
    end
    add_message "CheckResponse" do
      optional :is_member, :bool, 1
      optional :revision, :message, 2, "Zookie"
    end
    add_message "ExpandRequest" do
      optional :userset, :message, 1, "ObjectAndRelation"
      optional :at_revision, :message, 2, "Zookie"
    end
    add_message "ExpandResponse" do
      optional :tree_node, :message, 1, "RelationTupleTreeNode"
      optional :revision, :message, 3, "Zookie"
    end
  end
end

RelationTupleFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RelationTupleFilter").msgclass
RelationTupleFilter::Filter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RelationTupleFilter.Filter").enummodule
ReadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReadRequest").msgclass
ReadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReadResponse").msgclass
ReadResponse::Tupleset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReadResponse.Tupleset").msgclass
WriteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WriteRequest").msgclass
WriteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WriteResponse").msgclass
CheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckRequest").msgclass
ContentChangeCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ContentChangeCheckRequest").msgclass
CheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckResponse").msgclass
ExpandRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ExpandRequest").msgclass
ExpandResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ExpandResponse").msgclass
