# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: arrakisapi/api/acl_service.proto for package ''

require 'grpc'
require 'arrakisapi/api/acl_service_pb'

module ACLService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'ACLService'

    rpc :Read, ::ReadRequest, ::ReadResponse
    rpc :Write, ::WriteRequest, ::WriteResponse
    rpc :Check, ::CheckRequest, ::CheckResponse
    rpc :ContentChangeCheck, ::ContentChangeCheckRequest, ::CheckResponse
    rpc :Expand, ::ExpandRequest, ::ExpandResponse
  end

  Stub = Service.rpc_stub_class
end
