# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arrakisapi/api/core.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("arrakisapi/api/core.proto", :syntax => :proto3) do
    add_message "RelationTuple" do
      optional :object_and_relation, :message, 1, "ObjectAndRelation"
      optional :user, :message, 2, "User"
    end
    add_message "ObjectAndRelation" do
      optional :namespace, :string, 1
      optional :object_id, :string, 2
      optional :relation, :string, 3
    end
    add_message "User" do
      oneof :user_oneof do
        optional :user_id, :uint64, 1
        optional :userset, :message, 2, "ObjectAndRelation"
      end
    end
    add_message "Zookie" do
      optional :token, :string, 1
    end
    add_message "RelationTupleUpdate" do
      optional :operation, :enum, 1, "RelationTupleUpdate.Operation"
      optional :tuple, :message, 2, "RelationTuple"
    end
    add_enum "RelationTupleUpdate.Operation" do
      value :UNKNOWN, 0
      value :CREATE, 1
      value :TOUCH, 2
      value :DELETE, 3
    end
    add_message "RelationTupleTreeNode" do
      optional :expanded, :message, 3, "ObjectAndRelation"
      oneof :node_type do
        optional :intermediate_node, :message, 1, "SetOperationUserset"
        optional :leaf_node, :message, 2, "DirectUserset"
      end
    end
    add_message "SetOperationUserset" do
      optional :operation, :enum, 1, "SetOperationUserset.Operation"
      repeated :child_nodes, :message, 2, "RelationTupleTreeNode"
    end
    add_enum "SetOperationUserset.Operation" do
      value :INVALID, 0
      value :UNION, 1
      value :INTERSECTION, 2
      value :EXCLUSION, 3
    end
    add_message "DirectUserset" do
      repeated :users, :message, 1, "User"
    end
  end
end

RelationTuple = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RelationTuple").msgclass
ObjectAndRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ObjectAndRelation").msgclass
User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
Zookie = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Zookie").msgclass
RelationTupleUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RelationTupleUpdate").msgclass
RelationTupleUpdate::Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RelationTupleUpdate.Operation").enummodule
RelationTupleTreeNode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RelationTupleTreeNode").msgclass
SetOperationUserset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetOperationUserset").msgclass
SetOperationUserset::Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetOperationUserset.Operation").enummodule
DirectUserset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DirectUserset").msgclass
