# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: arrakisapi/api/namespace_service.proto for package ''

require 'grpc'
require 'arrakisapi/api/namespace_service_pb'

module NamespaceService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'NamespaceService'

    rpc :ReadConfig, ::ReadConfigRequest, ::ReadConfigResponse
    rpc :WriteConfig, ::WriteConfigRequest, ::WriteConfigResponse
  end

  Stub = Service.rpc_stub_class
end
