# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arrakisapi/api/namespace_service.proto

require 'google/protobuf'

require 'arrakisapi/api/core_pb'
require 'arrakisapi/api/namespace_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("arrakisapi/api/namespace_service.proto", :syntax => :proto3) do
    add_message "ReadConfigRequest" do
      optional :namespace, :string, 1
      optional :at_revision, :message, 2, "Zookie"
    end
    add_message "ReadConfigResponse" do
      optional :namespace, :string, 1
      optional :config, :message, 2, "NamespaceDefinition"
      optional :revision, :message, 4, "Zookie"
    end
    add_message "WriteConfigRequest" do
      optional :config, :message, 2, "NamespaceDefinition"
    end
    add_message "WriteConfigResponse" do
      optional :revision, :message, 1, "Zookie"
    end
  end
end

ReadConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReadConfigRequest").msgclass
ReadConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReadConfigResponse").msgclass
WriteConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WriteConfigRequest").msgclass
WriteConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WriteConfigResponse").msgclass
