# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arrakisapi/api/namespace.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("arrakisapi/api/namespace.proto", :syntax => :proto3) do
    add_message "NamespaceDefinition" do
      optional :name, :string, 1
      repeated :relation, :message, 2, "Relation"
    end
    add_message "Relation" do
      optional :name, :string, 1
      optional :userset_rewrite, :message, 2, "UsersetRewrite"
    end
    add_message "UsersetRewrite" do
      oneof :rewrite_operation do
        optional :union, :message, 1, "SetOperation"
        optional :intersection, :message, 2, "SetOperation"
        optional :exclusion, :message, 3, "SetOperation"
      end
    end
    add_message "SetOperation" do
      repeated :child, :message, 1, "SetOperation.Child"
    end
    add_message "SetOperation.Child" do
      oneof :child_type do
        optional :_this, :message, 1, "SetOperation.Child.This"
        optional :computed_userset, :message, 2, "ComputedUserset"
        optional :tuple_to_userset, :message, 3, "TupleToUserset"
        optional :userset_rewrite, :message, 4, "UsersetRewrite"
      end
    end
    add_message "SetOperation.Child.This" do
    end
    add_message "TupleToUserset" do
      optional :tupleset, :message, 1, "TupleToUserset.Tupleset"
      optional :computed_userset, :message, 2, "ComputedUserset"
    end
    add_message "TupleToUserset.Tupleset" do
      optional :relation, :string, 1
    end
    add_message "ComputedUserset" do
      optional :object, :enum, 1, "ComputedUserset.Object"
      optional :relation, :string, 2
    end
    add_enum "ComputedUserset.Object" do
      value :TUPLE_OBJECT, 0
      value :TUPLE_USERSET_OBJECT, 1
    end
  end
end

NamespaceDefinition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NamespaceDefinition").msgclass
Relation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Relation").msgclass
UsersetRewrite = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UsersetRewrite").msgclass
SetOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetOperation").msgclass
SetOperation::Child = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetOperation.Child").msgclass
SetOperation::Child::This = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetOperation.Child.This").msgclass
TupleToUserset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TupleToUserset").msgclass
TupleToUserset::Tupleset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TupleToUserset.Tupleset").msgclass
ComputedUserset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ComputedUserset").msgclass
ComputedUserset::Object = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ComputedUserset.Object").enummodule
