# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arrakisapi/api/watch_service.proto

require 'google/protobuf'

require 'arrakisapi/api/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("arrakisapi/api/watch_service.proto", :syntax => :proto3) do
    add_message "WatchRequest" do
      repeated :namespaces, :string, 1
      optional :start_revision, :message, 2, "Zookie"
    end
    add_message "WatchResponse" do
      repeated :updates, :message, 1, "RelationTupleUpdate"
      optional :end_revision, :message, 2, "Zookie"
    end
  end
end

WatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatchRequest").msgclass
WatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatchResponse").msgclass
