# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: arrakisapi/api/watch_service.proto for package ''

require 'grpc'
require 'arrakisapi/api/watch_service_pb'

module WatchService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'WatchService'

    rpc :Watch, ::WatchRequest, stream(::WatchResponse)
  end

  Stub = Service.rpc_stub_class
end
