# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/materialize/v0/relationships.proto

require 'google/protobuf'

require 'authzed/api/v1/core_pb'
require 'authzed/api/v1/permission_service_pb'
require 'buf/validate/validate_pb'
require 'validate/validate_pb'


descriptor_data = "\n.authzed/api/materialize/v0/relationships.proto\x12\x1a\x61uthzed.api.materialize.v0\x1a\x19\x61uthzed/api/v1/core.proto\x1a\'authzed/api/v1/permission_service.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x17validate/validate.proto\"\x94\x01\n-ExperimentalCountRelationshipsByFilterRequest\x12\x63\n\x13relationship_filter\x18\x01 \x01(\x0b\x32\".authzed.api.v1.RelationshipFilterB\x0e\xfa\x42\x05\x8a\x01\x02\x10\x01\xbaH\x03\xc8\x01\x01R\x12relationshipFilter\"\xa2\x01\n.ExperimentalCountRelationshipsByFilterResponse\x12-\n\x12relationship_count\x18\x01 \x01(\x04R\x11relationshipCount\x12\x41\n\x07read_at\x18\x02 \x01(\x0b\x32\x18.authzed.api.v1.ZedTokenB\x0e\xfa\x42\x05\x8a\x01\x02\x10\x01\xbaH\x03\xc8\x01\x01R\x06readAt2\xda\x01\n\x14RelationshipsService\x12\xc1\x01\n&ExperimentalCountRelationshipsByFilter\x12I.authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest\x1aJ.authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse\"\x00\x42\x62\n\x1e\x63om.authzed.api.materialize.v0P\x01Z>github.com/authzed/authzed-go/proto/authzed/api/materialize/v0b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Authzed
  module Api
    module Materialize
      module V0
        ExperimentalCountRelationshipsByFilterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest").msgclass
        ExperimentalCountRelationshipsByFilterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse").msgclass
      end
    end
  end
end
