# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authzed/api/materialize/v0/relationships.proto for package 'authzed.api.materialize.v0'

require 'grpc'
require 'authzed/api/materialize/v0/relationships_pb'

module Authzed
  module Api
    module Materialize
      module V0
        module RelationshipsService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'authzed.api.materialize.v0.RelationshipsService'

            # EXPERIMENTAL: CountRelationships returns the count of relationships for a given filter.
            rpc :ExperimentalCountRelationshipsByFilter, ::Authzed::Api::Materialize::V0::ExperimentalCountRelationshipsByFilterRequest, ::Authzed::Api::Materialize::V0::ExperimentalCountRelationshipsByFilterResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
