# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/acl_service.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v0.RelationTupleFilter" do
    optional :namespace, :string, 1
    optional :object_id, :string, 2
    optional :relation, :string, 3
    optional :userset, :message, 5, "authzed.api.v0.ObjectAndRelation"
    repeated :filters, :enum, 6, "authzed.api.v0.RelationTupleFilter.Filter"
  end
  add_enum "authzed.api.v0.RelationTupleFilter.Filter" do
    value :UNKNOWN, 0
    value :OBJECT_ID, 1
    value :RELATION, 2
    value :USERSET, 4
  end
  add_message "authzed.api.v0.ReadRequest" do
    repeated :tuplesets, :message, 1, "authzed.api.v0.RelationTupleFilter"
    optional :at_revision, :message, 2, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.ReadResponse" do
    repeated :tuplesets, :message, 1, "authzed.api.v0.ReadResponse.Tupleset"
    optional :revision, :message, 2, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.ReadResponse.Tupleset" do
    repeated :tuples, :message, 1, "authzed.api.v0.RelationTuple"
  end
  add_message "authzed.api.v0.WriteRequest" do
    repeated :write_conditions, :message, 1, "authzed.api.v0.RelationTuple"
    repeated :updates, :message, 2, "authzed.api.v0.RelationTupleUpdate"
  end
  add_message "authzed.api.v0.WriteResponse" do
    optional :revision, :message, 1, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.CheckRequest" do
    optional :test_userset, :message, 1, "authzed.api.v0.ObjectAndRelation"
    optional :user, :message, 2, "authzed.api.v0.User"
    optional :at_revision, :message, 3, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.ContentChangeCheckRequest" do
    optional :test_userset, :message, 1, "authzed.api.v0.ObjectAndRelation"
    optional :user, :message, 2, "authzed.api.v0.User"
  end
  add_message "authzed.api.v0.CheckResponse" do
    optional :is_member, :bool, 1
    optional :revision, :message, 2, "authzed.api.v0.Zookie"
    optional :membership, :enum, 3, "authzed.api.v0.CheckResponse.Membership"
  end
  add_enum "authzed.api.v0.CheckResponse.Membership" do
    value :UNKNOWN, 0
    value :NOT_MEMBER, 1
    value :MEMBER, 2
  end
  add_message "authzed.api.v0.ExpandRequest" do
    optional :userset, :message, 1, "authzed.api.v0.ObjectAndRelation"
    optional :at_revision, :message, 2, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.ExpandResponse" do
    optional :tree_node, :message, 1, "authzed.api.v0.RelationTupleTreeNode"
    optional :revision, :message, 3, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.LookupRequest" do
    optional :object_relation, :message, 1, "authzed.api.v0.RelationReference"
    optional :user, :message, 2, "authzed.api.v0.ObjectAndRelation"
    optional :at_revision, :message, 3, "authzed.api.v0.Zookie"
    optional :page_reference, :string, 4
    optional :limit, :uint32, 5
  end
  add_message "authzed.api.v0.LookupResponse" do
    repeated :resolved_object_ids, :string, 1
    optional :next_page_reference, :string, 2
    optional :revision, :message, 3, "authzed.api.v0.Zookie"
  end
end

module Authzed
  module Api
    module V0
      RelationTupleFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RelationTupleFilter").msgclass
      RelationTupleFilter::Filter = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RelationTupleFilter.Filter").enummodule
      ReadRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadRequest").msgclass
      ReadResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadResponse").msgclass
      ReadResponse::Tupleset = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadResponse.Tupleset").msgclass
      WriteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WriteRequest").msgclass
      WriteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WriteResponse").msgclass
      CheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.CheckRequest").msgclass
      ContentChangeCheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ContentChangeCheckRequest").msgclass
      CheckResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.CheckResponse").msgclass
      CheckResponse::Membership = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.CheckResponse.Membership").enummodule
      ExpandRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ExpandRequest").msgclass
      ExpandResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ExpandResponse").msgclass
      LookupRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupRequest").msgclass
      LookupResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupResponse").msgclass
    end
  end
end
