# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/core.proto

require 'google/protobuf'

require 'validate/validate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v0/core.proto", :syntax => :proto3) do
    add_message "authzed.api.v0.RelationTuple" do
      optional :object_and_relation, :message, 1, "authzed.api.v0.ObjectAndRelation", json_name: "objectAndRelation"
      optional :user, :message, 2, "authzed.api.v0.User", json_name: "user"
    end
    add_message "authzed.api.v0.ObjectAndRelation" do
      optional :namespace, :string, 1, json_name: "namespace"
      optional :object_id, :string, 2, json_name: "objectId"
      optional :relation, :string, 3, json_name: "relation"
    end
    add_message "authzed.api.v0.RelationReference" do
      optional :namespace, :string, 1, json_name: "namespace"
      optional :relation, :string, 3, json_name: "relation"
    end
    add_message "authzed.api.v0.User" do
      oneof :user_oneof do
        optional :userset, :message, 2, "authzed.api.v0.ObjectAndRelation", json_name: "userset"
      end
    end
  end
end

module Authzed
  module Api
    module V0
      RelationTuple = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RelationTuple").msgclass
      ObjectAndRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ObjectAndRelation").msgclass
      RelationReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RelationReference").msgclass
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.User").msgclass
    end
  end
end
