# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
require 'authzed/api/v0/namespace_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v0.FormatSchemaRequest" do
    optional :schema, :string, 1
  end
  add_message "authzed.api.v0.FormatSchemaResponse" do
    optional :error, :message, 1, "authzed.api.v0.DeveloperError"
    optional :formatted_schema, :string, 2
  end
  add_message "authzed.api.v0.UpgradeSchemaRequest" do
    repeated :namespace_configs, :string, 1
  end
  add_message "authzed.api.v0.UpgradeSchemaResponse" do
    optional :error, :message, 1, "authzed.api.v0.DeveloperError"
    optional :upgraded_schema, :string, 2
  end
  add_message "authzed.api.v0.ShareRequest" do
    optional :schema, :string, 1
    optional :relationships_yaml, :string, 2
    optional :validation_yaml, :string, 3
    optional :assertions_yaml, :string, 4
  end
  add_message "authzed.api.v0.ShareResponse" do
    optional :share_reference, :string, 1
  end
  add_message "authzed.api.v0.LookupShareRequest" do
    optional :share_reference, :string, 1
  end
  add_message "authzed.api.v0.LookupShareResponse" do
    optional :status, :enum, 1, "authzed.api.v0.LookupShareResponse.LookupStatus"
    optional :schema, :string, 2
    optional :relationships_yaml, :string, 3
    optional :validation_yaml, :string, 4
    optional :assertions_yaml, :string, 5
  end
  add_enum "authzed.api.v0.LookupShareResponse.LookupStatus" do
    value :UNKNOWN_REFERENCE, 0
    value :FAILED_TO_LOOKUP, 1
    value :VALID_REFERENCE, 2
    value :UPGRADED_REFERENCE, 3
  end
  add_message "authzed.api.v0.RequestContext" do
    optional :schema, :string, 1
    repeated :relationships, :message, 2, "authzed.api.v0.RelationTuple"
    repeated :legacy_ns_configs, :message, 3, "authzed.api.v0.NamespaceDefinition"
  end
  add_message "authzed.api.v0.EditCheckRequest" do
    optional :context, :message, 1, "authzed.api.v0.RequestContext"
    repeated :check_relationships, :message, 2, "authzed.api.v0.RelationTuple"
  end
  add_message "authzed.api.v0.EditCheckResult" do
    optional :relationship, :message, 1, "authzed.api.v0.RelationTuple"
    optional :is_member, :bool, 2
    optional :error, :message, 3, "authzed.api.v0.DeveloperError"
  end
  add_message "authzed.api.v0.EditCheckResponse" do
    repeated :request_errors, :message, 1, "authzed.api.v0.DeveloperError"
    repeated :check_results, :message, 2, "authzed.api.v0.EditCheckResult"
  end
  add_message "authzed.api.v0.ValidateRequest" do
    optional :context, :message, 1, "authzed.api.v0.RequestContext"
    optional :validation_yaml, :string, 3
    optional :update_validation_yaml, :bool, 4
    optional :assertions_yaml, :string, 5
  end
  add_message "authzed.api.v0.ValidateResponse" do
    repeated :request_errors, :message, 1, "authzed.api.v0.DeveloperError"
    repeated :validation_errors, :message, 2, "authzed.api.v0.DeveloperError"
    optional :updated_validation_yaml, :string, 3
  end
  add_message "authzed.api.v0.DeveloperError" do
    optional :message, :string, 1
    optional :line, :uint32, 2
    optional :column, :uint32, 3
    optional :source, :enum, 4, "authzed.api.v0.DeveloperError.Source"
    optional :kind, :enum, 5, "authzed.api.v0.DeveloperError.ErrorKind"
    repeated :path, :string, 6
    optional :context, :string, 7
  end
  add_enum "authzed.api.v0.DeveloperError.Source" do
    value :UNKNOWN_SOURCE, 0
    value :SCHEMA, 1
    value :RELATIONSHIP, 2
    value :VALIDATION_YAML, 3
    value :CHECK_WATCH, 4
    value :ASSERTION, 5
  end
  add_enum "authzed.api.v0.DeveloperError.ErrorKind" do
    value :UNKNOWN_KIND, 0
    value :PARSE_ERROR, 1
    value :SCHEMA_ISSUE, 2
    value :DUPLICATE_RELATIONSHIP, 3
    value :MISSING_EXPECTED_RELATIONSHIP, 4
    value :EXTRA_RELATIONSHIP_FOUND, 5
    value :UNKNOWN_OBJECT_TYPE, 6
    value :UNKNOWN_RELATION, 7
    value :MAXIMUM_RECURSION, 8
    value :ASSERTION_FAILED, 9
  end
end

module Authzed
  module Api
    module V0
      FormatSchemaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.FormatSchemaRequest").msgclass
      FormatSchemaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.FormatSchemaResponse").msgclass
      UpgradeSchemaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.UpgradeSchemaRequest").msgclass
      UpgradeSchemaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.UpgradeSchemaResponse").msgclass
      ShareRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ShareRequest").msgclass
      ShareResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ShareResponse").msgclass
      LookupShareRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareRequest").msgclass
      LookupShareResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareResponse").msgclass
      LookupShareResponse::LookupStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareResponse.LookupStatus").enummodule
      RequestContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RequestContext").msgclass
      EditCheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckRequest").msgclass
      EditCheckResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckResult").msgclass
      EditCheckResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckResponse").msgclass
      ValidateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidateRequest").msgclass
      ValidateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidateResponse").msgclass
      DeveloperError = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeveloperError").msgclass
      DeveloperError::Source = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeveloperError.Source").enummodule
      DeveloperError::ErrorKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeveloperError.ErrorKind").enummodule
    end
  end
end
