# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
require 'authzed/api/v0/namespace_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v0/developer.proto", :syntax => :proto3) do
    add_message "authzed.api.v0.ShareRequest" do
      repeated :namespace_configs, :string, 1, json_name: "namespaceConfigs"
      optional :relation_tuples, :string, 2, json_name: "relationTuples"
      optional :validation_yaml, :string, 3, json_name: "validationYaml"
      optional :assertions_yaml, :string, 4, json_name: "assertionsYaml"
    end
    add_message "authzed.api.v0.ShareResponse" do
      optional :share_reference, :string, 1, json_name: "shareReference"
    end
    add_message "authzed.api.v0.LookupShareRequest" do
      optional :share_reference, :string, 1, json_name: "shareReference"
    end
    add_message "authzed.api.v0.LookupShareResponse" do
      optional :status, :enum, 1, "authzed.api.v0.LookupShareResponse.LookupStatus", json_name: "status"
      repeated :namespace_configs, :string, 2, json_name: "namespaceConfigs"
      optional :relation_tuples, :string, 3, json_name: "relationTuples"
      optional :validation_yaml, :string, 4, json_name: "validationYaml"
      optional :assertions_yaml, :string, 5, json_name: "assertionsYaml"
    end
    add_enum "authzed.api.v0.LookupShareResponse.LookupStatus" do
      value :UNKNOWN_REFERENCE, 0
      value :FAILED_TO_LOOKUP, 1
      value :VALID_REFERENCE, 2
    end
    add_message "authzed.api.v0.NamespaceContext" do
      optional :handle, :string, 1, json_name: "handle"
      optional :config, :string, 2, json_name: "config"
    end
    add_message "authzed.api.v0.RequestContext" do
      repeated :namespaces, :message, 1, "authzed.api.v0.NamespaceContext", json_name: "namespaces"
      repeated :tuples, :message, 2, "authzed.api.v0.RelationTuple", json_name: "tuples"
    end
    add_message "authzed.api.v0.NamespaceInformation" do
      optional :handle, :string, 1, json_name: "handle"
      optional :parsed, :message, 2, "authzed.api.v0.NamespaceDefinition", json_name: "parsed"
      repeated :errors, :message, 3, "authzed.api.v0.ValidationError", json_name: "errors"
    end
    add_message "authzed.api.v0.EditCheckRequest" do
      optional :context, :message, 1, "authzed.api.v0.RequestContext", json_name: "context"
      repeated :check_tuples, :message, 2, "authzed.api.v0.RelationTuple", json_name: "checkTuples"
    end
    add_message "authzed.api.v0.EditCheckResult" do
      optional :tuple, :message, 1, "authzed.api.v0.RelationTuple", json_name: "tuple"
      optional :is_member, :bool, 2, json_name: "isMember"
      optional :error, :message, 3, "authzed.api.v0.ValidationError", json_name: "error"
    end
    add_message "authzed.api.v0.EditCheckResponse" do
      repeated :context_namespaces, :message, 1, "authzed.api.v0.NamespaceInformation", json_name: "contextNamespaces"
      repeated :additional_errors, :message, 2, "authzed.api.v0.ValidationError", json_name: "additionalErrors"
      repeated :check_results, :message, 3, "authzed.api.v0.EditCheckResult", json_name: "checkResults"
    end
    add_message "authzed.api.v0.ValidateRequest" do
      optional :context, :message, 1, "authzed.api.v0.RequestContext", json_name: "context"
      optional :validation_yaml, :string, 3, json_name: "validationYaml"
      optional :update_validation_yaml, :bool, 4, json_name: "updateValidationYaml"
      optional :assertions_yaml, :string, 5, json_name: "assertionsYaml"
    end
    add_message "authzed.api.v0.ValidationError" do
      optional :message, :string, 1, json_name: "message"
      optional :line, :uint32, 2, json_name: "line"
      optional :column, :uint32, 3, json_name: "column"
      optional :source, :enum, 4, "authzed.api.v0.ValidationError.Source", json_name: "source"
      optional :kind, :enum, 5, "authzed.api.v0.ValidationError.ErrorKind", json_name: "kind"
      repeated :path, :string, 6, json_name: "path"
      optional :metadata, :string, 7, json_name: "metadata"
    end
    add_enum "authzed.api.v0.ValidationError.Source" do
      value :UNKNOWN_SOURCE, 0
      value :NAMESPACE_CONFIG, 1
      value :VALIDATION_TUPLE, 2
      value :VALIDATION_YAML, 3
      value :CHECK_WATCH, 4
      value :ASSERTION, 5
    end
    add_enum "authzed.api.v0.ValidationError.ErrorKind" do
      value :UNKNOWN_KIND, 0
      value :PARSE_ERROR, 1
      value :NAMESPACE_CONFIG_ISSUE, 2
      value :DUPLICATE_TUPLE, 3
      value :MISSING_EXPECTED_TUPLE, 4
      value :EXTRA_TUPLE_FOUND, 5
      value :UNKNOWN_NAMESPACE, 6
      value :UNKNOWN_RELATION, 7
      value :MAXIMUM_RECURSION, 8
      value :ASSERTION_FAILED, 9
    end
    add_message "authzed.api.v0.ValidateResponse" do
      repeated :context_namespaces, :message, 1, "authzed.api.v0.NamespaceInformation", json_name: "contextNamespaces"
      repeated :validation_errors, :message, 2, "authzed.api.v0.ValidationError", json_name: "validationErrors"
      optional :updated_validation_yaml, :string, 3, json_name: "updatedValidationYaml"
    end
  end
end

module Authzed
  module Api
    module V0
      ShareRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ShareRequest").msgclass
      ShareResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ShareResponse").msgclass
      LookupShareRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareRequest").msgclass
      LookupShareResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareResponse").msgclass
      LookupShareResponse::LookupStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareResponse.LookupStatus").enummodule
      NamespaceContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.NamespaceContext").msgclass
      RequestContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RequestContext").msgclass
      NamespaceInformation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.NamespaceInformation").msgclass
      EditCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckRequest").msgclass
      EditCheckResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckResult").msgclass
      EditCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckResponse").msgclass
      ValidateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidateRequest").msgclass
      ValidationError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidationError").msgclass
      ValidationError::Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidationError.Source").enummodule
      ValidationError::ErrorKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidationError.ErrorKind").enummodule
      ValidateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidateResponse").msgclass
    end
  end
end
