# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v0/developer.proto", :syntax => :proto3) do
    add_message "authzed.api.v0.FormatSchemaRequest" do
      optional :schema, :string, 1, json_name: "schema"
    end
    add_message "authzed.api.v0.FormatSchemaResponse" do
      optional :error, :message, 1, "authzed.api.v0.DeveloperError", json_name: "error"
      optional :formatted_schema, :string, 2, json_name: "formattedSchema"
    end
    add_message "authzed.api.v0.UpgradeSchemaRequest" do
      repeated :namespace_configs, :string, 1, json_name: "namespaceConfigs"
    end
    add_message "authzed.api.v0.UpgradeSchemaResponse" do
      optional :error, :message, 1, "authzed.api.v0.DeveloperError", json_name: "error"
      optional :upgraded_schema, :string, 2, json_name: "upgradedSchema"
    end
    add_message "authzed.api.v0.ShareRequest" do
      optional :schema, :string, 1, json_name: "schema"
      optional :relationships_yaml, :string, 2, json_name: "relationshipsYaml"
      optional :validation_yaml, :string, 3, json_name: "validationYaml"
      optional :assertions_yaml, :string, 4, json_name: "assertionsYaml"
    end
    add_message "authzed.api.v0.ShareResponse" do
      optional :share_reference, :string, 1, json_name: "shareReference"
    end
    add_message "authzed.api.v0.LookupShareRequest" do
      optional :share_reference, :string, 1, json_name: "shareReference"
    end
    add_message "authzed.api.v0.LookupShareResponse" do
      optional :status, :enum, 1, "authzed.api.v0.LookupShareResponse.LookupStatus", json_name: "status"
      optional :schema, :string, 2, json_name: "schema"
      optional :relationships_yaml, :string, 3, json_name: "relationshipsYaml"
      optional :validation_yaml, :string, 4, json_name: "validationYaml"
      optional :assertions_yaml, :string, 5, json_name: "assertionsYaml"
    end
    add_enum "authzed.api.v0.LookupShareResponse.LookupStatus" do
      value :UNKNOWN_REFERENCE, 0
      value :FAILED_TO_LOOKUP, 1
      value :VALID_REFERENCE, 2
      value :UPGRADED_REFERENCE, 3
    end
    add_message "authzed.api.v0.RequestContext" do
      optional :schema, :string, 1, json_name: "schema"
      repeated :relationships, :message, 2, "authzed.api.v0.RelationTuple", json_name: "relationships"
    end
    add_message "authzed.api.v0.EditCheckRequest" do
      optional :context, :message, 1, "authzed.api.v0.RequestContext", json_name: "context"
      repeated :check_relationships, :message, 2, "authzed.api.v0.RelationTuple", json_name: "checkRelationships"
    end
    add_message "authzed.api.v0.EditCheckResult" do
      optional :relationship, :message, 1, "authzed.api.v0.RelationTuple", json_name: "relationship"
      optional :is_member, :bool, 2, json_name: "isMember"
      optional :error, :message, 3, "authzed.api.v0.DeveloperError", json_name: "error"
    end
    add_message "authzed.api.v0.EditCheckResponse" do
      repeated :request_errors, :message, 1, "authzed.api.v0.DeveloperError", json_name: "requestErrors"
      repeated :check_results, :message, 2, "authzed.api.v0.EditCheckResult", json_name: "checkResults"
    end
    add_message "authzed.api.v0.ValidateRequest" do
      optional :context, :message, 1, "authzed.api.v0.RequestContext", json_name: "context"
      optional :validation_yaml, :string, 3, json_name: "validationYaml"
      optional :update_validation_yaml, :bool, 4, json_name: "updateValidationYaml"
      optional :assertions_yaml, :string, 5, json_name: "assertionsYaml"
    end
    add_message "authzed.api.v0.ValidateResponse" do
      repeated :request_errors, :message, 1, "authzed.api.v0.DeveloperError", json_name: "requestErrors"
      repeated :validation_errors, :message, 2, "authzed.api.v0.DeveloperError", json_name: "validationErrors"
      optional :updated_validation_yaml, :string, 3, json_name: "updatedValidationYaml"
    end
    add_message "authzed.api.v0.DeveloperError" do
      optional :message, :string, 1, json_name: "message"
      optional :line, :uint32, 2, json_name: "line"
      optional :column, :uint32, 3, json_name: "column"
      optional :source, :enum, 4, "authzed.api.v0.DeveloperError.Source", json_name: "source"
      optional :kind, :enum, 5, "authzed.api.v0.DeveloperError.ErrorKind", json_name: "kind"
      repeated :path, :string, 6, json_name: "path"
      optional :context, :string, 7, json_name: "context"
    end
    add_enum "authzed.api.v0.DeveloperError.Source" do
      value :UNKNOWN_SOURCE, 0
      value :SCHEMA, 1
      value :RELATIONSHIP, 2
      value :VALIDATION_YAML, 3
      value :CHECK_WATCH, 4
      value :ASSERTION, 5
    end
    add_enum "authzed.api.v0.DeveloperError.ErrorKind" do
      value :UNKNOWN_KIND, 0
      value :PARSE_ERROR, 1
      value :SCHEMA_ISSUE, 2
      value :DUPLICATE_RELATIONSHIP, 3
      value :MISSING_EXPECTED_RELATIONSHIP, 4
      value :EXTRA_RELATIONSHIP_FOUND, 5
      value :UNKNOWN_OBJECT_TYPE, 6
      value :UNKNOWN_RELATION, 7
      value :MAXIMUM_RECURSION, 8
      value :ASSERTION_FAILED, 9
    end
  end
end

module Authzed
  module Api
    module V0
      FormatSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.FormatSchemaRequest").msgclass
      FormatSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.FormatSchemaResponse").msgclass
      UpgradeSchemaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.UpgradeSchemaRequest").msgclass
      UpgradeSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.UpgradeSchemaResponse").msgclass
      ShareRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ShareRequest").msgclass
      ShareResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ShareResponse").msgclass
      LookupShareRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareRequest").msgclass
      LookupShareResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareResponse").msgclass
      LookupShareResponse::LookupStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.LookupShareResponse.LookupStatus").enummodule
      RequestContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.RequestContext").msgclass
      EditCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckRequest").msgclass
      EditCheckResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckResult").msgclass
      EditCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.EditCheckResponse").msgclass
      ValidateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidateRequest").msgclass
      ValidateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ValidateResponse").msgclass
      DeveloperError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeveloperError").msgclass
      DeveloperError::Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeveloperError.Source").enummodule
      DeveloperError::ErrorKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeveloperError.ErrorKind").enummodule
    end
  end
end
