# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/namespace_service.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
require 'authzed/api/v0/namespace_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v0.ReadConfigRequest" do
    optional :namespace, :string, 1
    optional :at_revision, :message, 2, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.ReadConfigResponse" do
    optional :namespace, :string, 1
    optional :config, :message, 2, "authzed.api.v0.NamespaceDefinition"
    optional :revision, :message, 4, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.WriteConfigRequest" do
    repeated :configs, :message, 2, "authzed.api.v0.NamespaceDefinition"
  end
  add_message "authzed.api.v0.WriteConfigResponse" do
    optional :revision, :message, 1, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.DeleteConfigsRequest" do
    repeated :namespaces, :string, 1
  end
  add_message "authzed.api.v0.DeleteConfigsResponse" do
    optional :revision, :message, 1, "authzed.api.v0.Zookie"
  end
end

module Authzed
  module Api
    module V0
      ReadConfigRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadConfigRequest").msgclass
      ReadConfigResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadConfigResponse").msgclass
      WriteConfigRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WriteConfigRequest").msgclass
      WriteConfigResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WriteConfigResponse").msgclass
      DeleteConfigsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeleteConfigsRequest").msgclass
      DeleteConfigsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.DeleteConfigsResponse").msgclass
    end
  end
end
