# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/namespace.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'authzed/api/v0/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v0.Metadata" do
    repeated :metadata_message, :message, 1, "google.protobuf.Any"
  end
  add_message "authzed.api.v0.NamespaceDefinition" do
    optional :name, :string, 1
    repeated :relation, :message, 2, "authzed.api.v0.Relation"
    optional :metadata, :message, 3, "authzed.api.v0.Metadata"
  end
  add_message "authzed.api.v0.Relation" do
    optional :name, :string, 1
    optional :userset_rewrite, :message, 2, "authzed.api.v0.UsersetRewrite"
    optional :type_information, :message, 3, "authzed.api.v0.TypeInformation"
    optional :metadata, :message, 4, "authzed.api.v0.Metadata"
  end
  add_message "authzed.api.v0.TypeInformation" do
    repeated :allowed_direct_relations, :message, 1, "authzed.api.v0.RelationReference"
  end
  add_message "authzed.api.v0.UsersetRewrite" do
    oneof :rewrite_operation do
      optional :union, :message, 1, "authzed.api.v0.SetOperation"
      optional :intersection, :message, 2, "authzed.api.v0.SetOperation"
      optional :exclusion, :message, 3, "authzed.api.v0.SetOperation"
    end
  end
  add_message "authzed.api.v0.SetOperation" do
    repeated :child, :message, 1, "authzed.api.v0.SetOperation.Child"
  end
  add_message "authzed.api.v0.SetOperation.Child" do
    oneof :child_type do
      optional :_this, :message, 1, "authzed.api.v0.SetOperation.Child.This"
      optional :computed_userset, :message, 2, "authzed.api.v0.ComputedUserset"
      optional :tuple_to_userset, :message, 3, "authzed.api.v0.TupleToUserset"
      optional :userset_rewrite, :message, 4, "authzed.api.v0.UsersetRewrite"
    end
  end
  add_message "authzed.api.v0.SetOperation.Child.This" do
  end
  add_message "authzed.api.v0.TupleToUserset" do
    optional :tupleset, :message, 1, "authzed.api.v0.TupleToUserset.Tupleset"
    optional :computed_userset, :message, 2, "authzed.api.v0.ComputedUserset"
  end
  add_message "authzed.api.v0.TupleToUserset.Tupleset" do
    optional :relation, :string, 1
  end
  add_message "authzed.api.v0.ComputedUserset" do
    optional :object, :enum, 1, "authzed.api.v0.ComputedUserset.Object"
    optional :relation, :string, 2
  end
  add_enum "authzed.api.v0.ComputedUserset.Object" do
    value :TUPLE_OBJECT, 0
    value :TUPLE_USERSET_OBJECT, 1
  end
end

module Authzed
  module Api
    module V0
      Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.Metadata").msgclass
      NamespaceDefinition = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.NamespaceDefinition").msgclass
      Relation = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.Relation").msgclass
      TypeInformation = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.TypeInformation").msgclass
      UsersetRewrite = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.UsersetRewrite").msgclass
      SetOperation = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.SetOperation").msgclass
      SetOperation::Child = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.SetOperation.Child").msgclass
      SetOperation::Child::This = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.SetOperation.Child.This").msgclass
      TupleToUserset = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.TupleToUserset").msgclass
      TupleToUserset::Tupleset = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.TupleToUserset.Tupleset").msgclass
      ComputedUserset = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ComputedUserset").msgclass
      ComputedUserset::Object = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ComputedUserset.Object").enummodule
    end
  end
end
