# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/namespace_service.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
require 'authzed/api/v0/namespace_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v0/namespace_service.proto", :syntax => :proto3) do
    add_message "authzed.api.v0.ReadConfigRequest" do
      optional :namespace, :string, 1, json_name: "namespace"
      optional :at_revision, :message, 2, "authzed.api.v0.Zookie", json_name: "atRevision"
    end
    add_message "authzed.api.v0.ReadConfigResponse" do
      optional :namespace, :string, 1, json_name: "namespace"
      optional :config, :message, 2, "authzed.api.v0.NamespaceDefinition", json_name: "config"
      optional :revision, :message, 4, "authzed.api.v0.Zookie", json_name: "revision"
    end
    add_message "authzed.api.v0.WriteConfigRequest" do
      repeated :configs, :message, 2, "authzed.api.v0.NamespaceDefinition", json_name: "configs"
    end
    add_message "authzed.api.v0.WriteConfigResponse" do
      optional :revision, :message, 1, "authzed.api.v0.Zookie", json_name: "revision"
    end
  end
end

module Authzed
  module Api
    module V0
      ReadConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadConfigRequest").msgclass
      ReadConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.ReadConfigResponse").msgclass
      WriteConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WriteConfigRequest").msgclass
      WriteConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WriteConfigResponse").msgclass
    end
  end
end
