# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authzed/api/v0/namespace_service.proto for package 'authzed.api.v0'

require 'grpc'
require 'authzed/api/v0/namespace_service_pb'

module Authzed
  module Api
    module V0
      module NamespaceService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'authzed.api.v0.NamespaceService'

          rpc :ReadConfig, ::Authzed::Api::V0::ReadConfigRequest, ::Authzed::Api::V0::ReadConfigResponse
          rpc :WriteConfig, ::Authzed::Api::V0::WriteConfigRequest, ::Authzed::Api::V0::WriteConfigResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
