# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/watch_service.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authzed/api/v0/watch_service.proto", :syntax => :proto3) do
    add_message "authzed.api.v0.WatchRequest" do
      repeated :namespaces, :string, 1, json_name: "namespaces"
      optional :start_revision, :message, 2, "authzed.api.v0.Zookie", json_name: "startRevision"
    end
    add_message "authzed.api.v0.WatchResponse" do
      repeated :updates, :message, 1, "authzed.api.v0.RelationTupleUpdate", json_name: "updates"
      optional :end_revision, :message, 2, "authzed.api.v0.Zookie", json_name: "endRevision"
    end
  end
end

module Authzed
  module Api
    module V0
      WatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WatchRequest").msgclass
      WatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WatchResponse").msgclass
    end
  end
end
