# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authzed/api/v0/watch_service.proto for package 'authzed.api.v0'

require 'grpc'
require 'authzed/api/v0/watch_service_pb'

module Authzed
  module Api
    module V0
      module WatchService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'authzed.api.v0.WatchService'

          rpc :Watch, ::Authzed::Api::V0::WatchRequest, stream(::Authzed::Api::V0::WatchResponse)
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
