# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/watch_service.proto

require 'google/protobuf'

require 'authzed/api/v0/core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authzed.api.v0.WatchRequest" do
    repeated :namespaces, :string, 1
    optional :start_revision, :message, 2, "authzed.api.v0.Zookie"
  end
  add_message "authzed.api.v0.WatchResponse" do
    repeated :updates, :message, 1, "authzed.api.v0.RelationTupleUpdate"
    optional :end_revision, :message, 2, "authzed.api.v0.Zookie"
  end
end

module Authzed
  module Api
    module V0
      WatchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WatchRequest").msgclass
      WatchResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("authzed.api.v0.WatchResponse").msgclass
    end
  end
end
