name: "build"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  test:
    name: "Test Clients"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7.3"
      - uses: "authzed/action-spicedb@v1"
      - name: "Install dependencies"
        run: "bundle install"
      - name: "Run rspec"
        run: "bundle exec rspec"

  protobuf:
    name: "Generate Protobufs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7.3"
      - uses: "arduino/setup-protoc@v2"
        with:
          version: "23.3"
      - name: "Install Homebrew & gRPC"
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install grpc
          which grpc_ruby_plugin
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
      - uses: "authzed/actions/buf-generate@main"
        with:
          version: "1.9.0"
