name: "build"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  test:
    name: "Test Clients"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - uses: "authzed/action-spicedb@v1"
      - name: "Install dependencies"
        run: "bundle install"
      - name: "Run rspec"
        run: "bundle exec rspec"

  protobuf:
    name: "Generate Protobufs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - uses: "arduino/setup-protoc@v3"
        with:
          version: "24.4"
      - name: "Install Homebrew & gRPC"
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install grpc
          which grpc_ruby_plugin
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
      - uses: "bufbuild/buf-setup-action@v1.36.0"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
