name: "Publish gem to Rubygems"
on:
  #push:
    #tags:
      #- '*'
  pull_request:
    branches:
    - "*"
  workflow_dispatch:
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Set up Ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - name: "Install deps"
        run: |
          gem install bundler
          bundle install
      # Set the version at release time
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set version within package
        run: "bundle exec gem bump --version 1.0.0 --no-commit"
      - name: "Build and publish to Rubygems"
        uses: "cadwallion/publish-rubygems-action@v1.1.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
          # NOTE: we override the release command because `rake release`
          # attempts to push a tag to the upstream repo and we don't
          # want that.
          RELEASE_COMMAND: "rake build && gem push pkg/..."
