name: "Publish gem to Rubygems"
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Set up Ruby"
        uses: "actions/setup-ruby@v1"
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: "Install deps"
        run: |
          gem install bundler
          bundle install
      - name: "Build and publish to Rubygems"
        uses: "cadwallion/publish-rubygems-action@v1.0.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RUBYGEMS_API_KEY : "${{ secrets.RUBYGEMS_API_KEY }}"
